### ISSUE TITLE
About the param_listener

### ISSUE THREAD

**Issue by facontidavide** [MarqRazz/ActionServer.BT#2]
Hi,

so, param listener is great, but I wonder if it should be inside ActionServerBT

https://github.com/MarqRazz/ActionServer.BT/blob/main/action_server_bt/include/action_server_bt/action_server_bt.hpp#L64

In other words, I would have expected something like this 

struct ActionServerParams {
   std::string action_name;
   int groot2_port;
   int behavior_tick_frequency;
   std::vector<std::string> plugins;
   std::vector<std::string> ros_plugins;
    std::vector<std::string> behavior_trees;
};

ActionServerBT::init(ActionServerParams params);
```

So, I know this is old fashion, but I would move the param listener to  **action_server_bt_node.cpp**

Thoughts?

**Comment by MarqRazz** [comment]
The reason that it's internal to the class is so that I can [dynamically reload the ROS parameters](https://github.com/MarqRazz/ActionServer.BT/blob/main/action_server_bt/src/action_server_bt.cpp#L88-L93) when a new action goal is sent and only when they have been updated.

If I move it out I would have to manually maintain when to sync the parameters so things don't change while the action server is executing.
